# Generated by Django 5.0.6 on 2024-07-27 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=150, verbose_name='what to do?')),
                ('description', models.TextField(blank=True, null=True, verbose_name='get into details if needed ...')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due to')),
                ('completed', models.CharField(choices=[('COMPLETED', 'Yes'), ('IN PROGRESS', 'No')], default='IN PROGRESS')),
                ('status', models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published')], default='DRAFT', max_length=10, verbose_name='status')),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.ManyToManyField(related_name='tasks', to='todolist_app.tag')),
            ],
            options={
                'verbose_name': 'TO-DO',
                'verbose_name_plural': 'TO-DOs',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='todolist_app.task')),
            ],
        ),
    ]
