# Generated by Django 5.0.6 on 2024-07-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'TO-DO', 'verbose_name_plural': 'TO-DOs'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='here get here into details if needed'),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='due to'),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='no name', max_length=150, verbose_name='what to do (here keep long story really short)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('COMPLETED', 'Yes'), ('IN PROGRESS', 'No')], default='IN PROGRESS'),
        ),
    ]
