# Generated by Django 5.0.6 on 2024-07-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_alter_task_options_remove_task_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.CharField(default='admin', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'draft'), ('PUBLISHED', 'published')], default='DRAFT', max_length=10, verbose_name='status'),
        ),
    ]
